$("h1").css("color", "blue");
$(".pricing").css("color", "blue");
$(".self").css("color", "blue");
$("button").css("font-size", "11pt");
$("a").css("color", "gold");
$("button").css("background-color", "blue");
$(".back-end").css("color", "blue");
$(".full-stack").css("color", "blue");
$(".projects").css("color", "blue");
